# Generated by Django 4.0.10 on 2025-07-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0016_data_update_sc_to_ic_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportunit',
            name='reason',
            field=models.CharField(blank=True, choices=[('IC', 'Inappropriate content'), ('GV', 'Graphic violence'), ('HA', 'Hateful or abusive content'), ('CI', 'Copycat or impersonation'), ('OO', 'Other objection')], default=None, max_length=2, null=True),
        ),
    ]
