# Generated by Django 4.2.20 on 2026-06-04 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    if getattr(settings, 'TESTING_MIGRATIONS', False):
        dependencies = [
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
            ('eox_nelp', '0017_alter_reportunit_reason'),
        ]
        course_overview_model = 'eox_nelp.courseoverview'
    else:
        dependencies = [
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
            ('course_overviews', '0029_alter_historicalcourseoverview_options'),
            ('eox_nelp', '0017_alter_reportunit_reason'),
        ]
        course_overview_model = 'course_overviews.courseoverview'

    operations = [
        migrations.AlterField(
            model_name='feedbackcourse',
            name='author',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackcourse',
            name='course_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=course_overview_model),
        ),
        migrations.AlterField(
            model_name='feedbackunit',
            name='author',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackunit',
            name='course_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=course_overview_model),
        ),
        migrations.AlterField(
            model_name='likedislikecourse',
            name='author',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likedislikecourse',
            name='course_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=course_overview_model),
        ),
        migrations.AlterField(
            model_name='likedislikeunit',
            name='author',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likedislikeunit',
            name='course_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=course_overview_model),
        ),
        migrations.AlterField(
            model_name='reportcourse',
            name='author',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportcourse',
            name='course_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=course_overview_model),
        ),
        migrations.AlterField(
            model_name='reportunit',
            name='author',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportunit',
            name='course_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=course_overview_model),
        ),
    ]
