# Generated by Django 4.2.20 on 2026-05-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0017_alter_reportunit_reason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedbackcourse',
            index=models.Index(fields=['author', 'course_id'], name='feedback_author_course_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackunit',
            index=models.Index(fields=['author', 'item_id'], name='feedback_author_item_idx'),
        ),
        migrations.AddIndex(
            model_name='likedislikecourse',
            index=models.Index(fields=['author', 'course_id'], name='likedislike_author_course_idx'),
        ),
        migrations.AddIndex(
            model_name='likedislikeunit',
            index=models.Index(fields=['author', 'item_id'], name='likedislike_author_item_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcourse',
            index=models.Index(fields=['author', 'course_id'], name='report_author_course_idx'),
        ),
        migrations.AddIndex(
            model_name='reportunit',
            index=models.Index(fields=['author', 'item_id'], name='report_author_item_idx'),
        ),
    ]
