# Generated by Django 4.0.10 on 2025-08-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0018_samlbulktemplateconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlbulktemplateconfiguration',
            name='slug_suffix',
            field=models.CharField(default='lms-sso', help_text="Suffix appended to the generated slug after removing the TLD. For example, with domain 'example.org' and suffix 'custom-idp', the slug becomes 'example-custom-idp'.", max_length=50),
        ),
    ]
