# Generated by Django 4.0.10 on 2025-08-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_nelp', '0019_samlbulktemplateconfiguration_slug_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlbulktemplateconfiguration',
            name='use_default_saml_configuration_slug',
            field=models.BooleanField(default=True, help_text='If checked, the slug for each site will be the default value defined in the model. If unchecked, a dynamic slug will be generated from the site domain and the `slug_suffix`.'),
        ),
    ]
